# -*- coding: utf-8 -*-
"""fab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AoMDfsd_HQx-7KmoSrS19sYyk9TCUByD
"""

!pip install fabric

from fabric import Connection
import platform
import socket

# Remote Windows VM credentials
REMOTE_HOST = "192.168.1.194"
USERNAME = "admin"
PASSWORD = "yankeeD00dle"

def get_local_host_info():
    """Fetch and display local host information."""
    print("Querying local host information...\n")
    hostname = socket.gethostname()
    ip_address = socket.gethostbyname(hostname)
    os_info = platform.system() + " " + platform.release()

    print(f"Hostname: {hostname}")
    print(f"IP Address: {ip_address}")
    print(f"OS Information: {os_info}\n")

def get_remote_host_info():
    """Fetch and display remote host information."""
    print("Querying remote host information...\n")
    try:
        # Connect to the remote Windows VM
        conn = Connection(
            host=REMOTE_HOST,
            user=USERNAME,
            connect_kwargs={"password": PASSWORD},
        )

        # Commands to fetch remote host details
        commands = {
            "Hostname": "hostname",
            "IP Address": "ipconfig | findstr IPv4",
            "OS Information": "ver",
        }

        for key, cmd in commands.items():
            result = conn.run(cmd, hide=True)
            print(f"{key}: {result.stdout.strip()}")

        print("\nRemote host information retrieved successfully!")

    except Exception as e:
        print(f"Error querying remote host: {e}")

if __name__ == "__main__":
    # Get information for both local and remote hosts
    get_local_host_info()
    get_remote_host_info()

